version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'gantry-ml/foreach']
    volumes:
      - ".:/plugin:ro"
  test:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"